import type { CharacterItem, KeywordTrend, PlatformShare, TrendPeriod } from "@/types/trend";

export const periodLabels: Record<TrendPeriod, string> = {
  daily: "Daily",
  weekly: "Weekly",
  monthly: "Monthly",
};

export const mockTrendingCharacters: CharacterItem[] = [
  {
    id: "char-001",
    characterName: "Seo Yuna",
    imageUrl: "https://via.placeholder.com/300x220/111827/2dd4bf?text=Seo+Yuna",
    serviceName: "Zeta",
    category: "ai_character",
    genreTags: ["Romance", "Healing"],
    chatCount: 84200,
    viewCount: 0,
  },
  {
    id: "char-002",
    characterName: "Kain",
    imageUrl: "https://via.placeholder.com/300x220/111827/38bdf8?text=Kain",
    serviceName: "Genit",
    category: "ai_character",
    genreTags: ["Fantasy", "Adventure"],
    chatCount: 79880,
    viewCount: 0,
  },
  {
    id: "char-003",
    characterName: "Harin",
    imageUrl: "https://via.placeholder.com/300x220/111827/fb7185?text=Harin",
    serviceName: "Crack",
    category: "ai_character",
    genreTags: ["Thriller", "Mystery"],
    chatCount: 76440,
    viewCount: 0,
  },
  {
    id: "char-004",
    characterName: "Leon",
    imageUrl: "https://via.placeholder.com/300x220/111827/fbbf24?text=Leon",
    serviceName: "Zeta",
    category: "ai_character",
    genreTags: ["Noir", "Action"],
    chatCount: 72130,
    viewCount: 0,
  },
  {
    id: "char-005",
    characterName: "Mia",
    imageUrl: "https://via.placeholder.com/300x220/111827/a78bfa?text=Mia",
    serviceName: "LunaTalk",
    category: "ai_character",
    genreTags: ["Idol", "Slice of Life"],
    chatCount: 68900,
    viewCount: 0,
  },
  {
    id: "char-006",
    characterName: "Dohyun",
    imageUrl: "https://via.placeholder.com/300x220/111827/22c55e?text=Dohyun",
    serviceName: "Genit",
    category: "ai_character",
    genreTags: ["School", "Romance"],
    chatCount: 65100,
    viewCount: 0,
  },
  {
    id: "char-007",
    characterName: "Lucy",
    imageUrl: "https://via.placeholder.com/300x220/111827/ec4899?text=Lucy",
    serviceName: "Crack",
    category: "ai_character",
    genreTags: ["Sci-Fi", "Cyberpunk"],
    chatCount: 62840,
    viewCount: 0,
  },
  {
    id: "char-008",
    characterName: "Ian",
    imageUrl: "https://via.placeholder.com/300x220/111827/06b6d4?text=Ian",
    serviceName: "Zeta",
    category: "ai_character",
    genreTags: ["Office", "Romance"],
    chatCount: 59420,
    viewCount: 0,
  },
  {
    id: "char-009",
    characterName: "Arin",
    imageUrl: "https://via.placeholder.com/300x220/111827/84cc16?text=Arin",
    serviceName: "Genit",
    category: "ai_character",
    genreTags: ["Fantasy", "Magic"],
    chatCount: 56880,
    viewCount: 0,
  },
  {
    id: "char-010",
    characterName: "Noah",
    imageUrl: "https://via.placeholder.com/300x220/111827/f97316?text=Noah",
    serviceName: "Crack",
    category: "ai_character",
    genreTags: ["Detective", "Thriller"],
    chatCount: 54290,
    viewCount: 0,
  },
  {
    id: "char-011",
    characterName: "Sera",
    imageUrl: "https://via.placeholder.com/300x220/111827/14b8a6?text=Sera",
    serviceName: "LunaTalk",
    category: "ai_character",
    genreTags: ["Healing", "Counseling"],
    chatCount: 52410,
    viewCount: 0,
  },
  {
    id: "char-012",
    characterName: "Jinwoo",
    imageUrl: "https://via.placeholder.com/300x220/111827/60a5fa?text=Jinwoo",
    serviceName: "Zeta",
    category: "ai_character",
    genreTags: ["Martial Arts", "Growth"],
    chatCount: 50130,
    viewCount: 0,
  },
];

export const trendingKeywords: KeywordTrend[] = [
  { keyword: "Contract Romance", delta: 38 },
  { keyword: "Villain Return", delta: 31 },
  { keyword: "After Work Comfort", delta: 27 },
  { keyword: "Idol Manager", delta: 22 },
  { keyword: "Cyber Detective", delta: 18 },
];

export const genreDistribution: PlatformShare[] = [
  { name: "Romance", value: 34, color: "#2dd4bf" },
  { name: "Fantasy", value: 25, color: "#38bdf8" },
  { name: "Thriller", value: 18, color: "#fb7185" },
  { name: "Healing", value: 13, color: "#fbbf24" },
  { name: "Sci-Fi", value: 10, color: "#a78bfa" },
];
